import './globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from '@/app/context/auth-context';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EdCoach AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className+" dark"}>
        <AuthContextProvider>
        {children}
                
        </AuthContextProvider>
      </body>
    </html>
  )
}
